# Copia este archivo como application-local.yaml y rellena tus valores.
# NUNCA subas application-local.yaml a GitHub.

spring:
  datasource:
    url: jdbc:postgresql://ep-sparkling-tree-ac9xtymj-pooler.sa-east-1.aws.neon.tech/sofagamesdb?sslmode=require
    username: neondb_owner
    password: REEMPLAZAR

jwt:
  secret: REEMPLAZAR_con_string_aleatorio_minimo_32_caracteres